-- 0001_api_clients.sql — per-client API credentials (replaces the old
-- single shared WORKER_API_KEY secret).
--
-- Apply with: wrangler d1 execute forex-signals-db --file=./migrations/0001_api_clients.sql
-- Idempotent (CREATE TABLE IF NOT EXISTS). Never destructive.

CREATE TABLE IF NOT EXISTS api_clients (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the provision script
  client_id TEXT NOT NULL UNIQUE,      -- e.g. "bridge", "app", "agent"
  secret_hash TEXT NOT NULL,           -- SHA-256 hex of the client secret (never the raw secret)
  label TEXT,                          -- human note, e.g. "Windows MT5 bridge"
  revoked INTEGER NOT NULL DEFAULT 0,  -- 1 = credentials rejected
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_api_clients_client_id ON api_clients(client_id);
