-- D1 schema for the forex signal bot backend.
-- Apply with: wrangler d1 execute forex-signals-db --file=./schema.sql

CREATE TABLE IF NOT EXISTS signals (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the Worker
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  direction TEXT NOT NULL,             -- BUY | SELL
  entry_price REAL NOT NULL,
  stop_loss REAL NOT NULL,
  take_profit REAL NOT NULL,
  ema_fast REAL,
  ema_slow REAL,
  rsi_value REAL,
  atr_value REAL,
  candle_time TEXT NOT NULL,           -- ISO timestamp of the closed candle that fired the signal
  trigger_text TEXT,                   -- e.g. "EMA20 crossed above EMA50, RSI=58.2"
  ai_reasoning TEXT,                   -- plain-English explanation from the configured AI provider
  ai_confidence INTEGER,               -- 0-100, model's stated confidence, may be NULL if unparsed
  ai_risk_notes TEXT,                  -- concerns raised by the model OR by our own correlation check
  ai_tool_calls TEXT,                  -- JSON array of {tool, input} the agent actually called (Anthropic path only, NULL for fallback path)
  ai_decision TEXT,                    -- 'enter' | 'skip' | NULL — the agent's own verdict, distinct from human approval

  -- Real cost data — see forex-bot-bridge/cost_tracking.py and
  -- worker_client.py. spread_at_entry/lot_size come from the actual
  -- order execution result; commission/swap come from MT5's real deal
  -- history at close time, not an estimate.
  spread_at_entry REAL,                -- ask - bid at the moment of execution, in raw price units
  lot_size REAL,                       -- confirmed position size from the order result
  commission REAL,                     -- real commission charged, summed across entry+exit deals
  swap REAL,                           -- real swap/overnight financing charged, summed across all deals

  -- Persisted for the app to actually consume later, not just for the
  -- agent's same-request tool calls. Previously these were forwarded by
  -- the bridge but never stored, which meant the app's candlestick chart
  -- silently never had real data by the time a GET request reached it —
  -- fixed here rather than left quietly broken.
  recent_candles TEXT,                 -- JSON array of {time,open,high,low,close}
  smc_summary TEXT,                    -- JSON — see smc_analysis.py's analyze() output shape
  symbol_specs TEXT,                   -- JSON {tick_value,tick_size,contract_size,digits} — real broker data, see mt5_client.get_symbol_trade_specs

  -- status lifecycle:
  -- pending -> approved -> executed -> closed
  --         -> rejected_by_user
  --         -> skipped_by_agent        (autonomous mode: agent's own decision was "skip")
  --         (approved) -> rejected_by_risk   (bridge's risk.py rejected it after approval)
  --         (approved) -> failed             (MT5 order_send failed)
  -- Note: in autonomous mode, signals skip 'pending' and go straight to
  -- 'approved' ONLY if the agent's decision was 'enter' (see db.js
  -- autoApproveIfAutonomous and index.js). A 'skip' decision in
  -- autonomous mode goes to 'skipped_by_agent' instead — the agent is
  -- the trader now, not just a commentator on the deterministic signal.
  status TEXT NOT NULL DEFAULT 'pending',

  mt5_result TEXT,                     -- JSON blob of the MT5 order result, once executed
  rejection_reason TEXT,

  -- Populated by exit_manager.py when it closes a position autonomously
  -- (trailing stop hit, breakeven stop hit, or time-based exit).
  closed_reason TEXT,
  closed_price REAL,
  closed_at TEXT,

  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);

-- Device push tokens for FCM. Supports multiple devices per install.
CREATE TABLE IF NOT EXISTS device_tokens (
  token TEXT PRIMARY KEY,
  registered_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_seen_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Simple key-value settings store. Currently used for:
--   trading_mode: 'manual' | 'autonomous'  (default 'manual' — see db.js)
--   kill_switch_engaged, kill_switch_close_all_requested_at
--   custom_ai_url, custom_ai_api_key — app-configured self-hosted model
--     connection (e.g. an Alibaba VM), overrides deploy-time env when set
--     (see agent/dynamicSettings.js)
-- Defaults to manual if no row exists, so a fresh deploy never
-- silently starts trading without approval.
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Real performance snapshots reported by performance_review.py, computed
-- from MT5's actual deal history — ground truth, not our own approximation.
CREATE TABLE IF NOT EXISTS performance_snapshots (
  id TEXT PRIMARY KEY,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  total_closed_trades INTEGER NOT NULL,
  wins INTEGER NOT NULL,
  losses INTEGER NOT NULL,
  breakeven INTEGER NOT NULL,
  win_rate_pct REAL,
  total_profit REAL NOT NULL,
  average_win REAL,
  average_loss REAL,
  profit_factor REAL,
  largest_win REAL,
  largest_loss REAL,
  by_symbol TEXT,                      -- JSON blob
  -- Real costs, summed from MT5's actual deal history across the same
  -- window — total_profit above is price-movement P/L only; net_profit
  -- is what actually happened to the account balance.
  total_commission REAL,
  total_swap REAL,
  net_profit REAL,                     -- total_profit + total_commission + total_swap
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_performance_created_at ON performance_snapshots(created_at);

-- Post-trade reflections: generated when a signal closes, referencing the
-- ORIGINAL reasoning against the ACTUAL outcome. This is retrieval-augmented
-- experience, not model fine-tuning — the underlying model's weights never
-- change, but future decisions can retrieve and reference past reflections
-- via the get_past_reflections tool, which is a real (if bounded) way for
-- the system to avoid repeating a documented mistake.
CREATE TABLE IF NOT EXISTS reflections (
  id TEXT PRIMARY KEY,
  signal_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  direction TEXT NOT NULL,
  outcome TEXT NOT NULL,               -- 'win' | 'loss' | 'breakeven'
  entry_price REAL NOT NULL,
  closed_price REAL NOT NULL,
  original_reasoning TEXT,
  original_confidence INTEGER,
  reflection_text TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (signal_id) REFERENCES signals(id)
);

CREATE INDEX IF NOT EXISTS idx_reflections_symbol ON reflections(symbol);
CREATE INDEX IF NOT EXISTS idx_reflections_created_at ON reflections(created_at);

-- Chart data for the app's Charts tab — genuinely independent of the
-- signal pipeline, unlike signals.recent_candles (which exists only as
-- evidence for one specific trade decision). Refreshed on a schedule by
-- chart_data_loop in main.py, NOT live/streaming — updated_at is exposed
-- to the app precisely so it can show real staleness rather than imply
-- real-time data it doesn't have.
CREATE TABLE IF NOT EXISTS chart_data (
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  candles TEXT NOT NULL,                -- JSON array of {time,open,high,low,close}
  ema_fast TEXT,                        -- JSON array, same length as candles, null-padded before warmup
  ema_slow TEXT,
  ema_fast_period INTEGER,
  ema_slow_period INTEGER,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (symbol, timeframe)
);
