-- D1 schema for the forex-agent cloud/sync layer.
--
-- This file is the CANONICAL FULL SCHEMA for FRESH deploys:
--   wrangler d1 execute forex-signals-db --file=./schema.sql
--
-- For EXISTING databases, never re-run destructive statements — apply
-- ./migrations/*.sql in numeric order instead (append-only, additive).
-- schema.sql and the migrations together describe the same final schema;
-- migrations exist so existing D1 data always survives a Worker update.

CREATE TABLE IF NOT EXISTS signals (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the Worker
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  direction TEXT NOT NULL,             -- BUY | SELL
  entry_price REAL NOT NULL,
  stop_loss REAL NOT NULL,
  take_profit REAL NOT NULL,
  ema_fast REAL,
  ema_slow REAL,
  rsi_value REAL,
  atr_value REAL,
  candle_time TEXT NOT NULL,           -- ISO timestamp of the closed candle that fired the signal
  trigger_text TEXT,                   -- e.g. "EMA20 crossed above EMA50, RSI=58.2"
  -- ai_* columns are kept for backward compatibility with existing rows
  -- and are now written by the SUBSYSTEM / external agent, never by the
  -- Worker (the Worker performs no AI reasoning). New signals reported
  -- via POST /signals store NULL here.
  ai_reasoning TEXT,                   -- plain-English explanation from the external agent
  ai_confidence INTEGER,               -- 0-100, may be NULL
  ai_risk_notes TEXT,                  -- concerns from the agent AND/OR the subsystem's deterministic correlation check
  ai_tool_calls TEXT,                  -- JSON array of {tool, input} (NULL when unused)
  ai_decision TEXT,                    -- 'enter' | 'skip' | NULL — the external agent's own verdict

  -- Real cost data — see forex-bot-bridge/cost_tracking.py and
  -- worker_client.py. spread_at_entry/lot_size come from the actual
  -- order execution result; commission/swap come from MT5's real deal
  -- history at close time, not an estimate.
  spread_at_entry REAL,                -- ask - bid at the moment of execution, in raw price units
  lot_size REAL,                       -- confirmed position size from the order result
  commission REAL,                     -- real commission charged, summed across entry+exit deals
  swap REAL,                           -- real swap/overnight financing charged, summed across all deals

  -- Persisted for the app to actually consume later, not just for the
  -- agent's same-request tool calls. Previously these were forwarded by
  -- the bridge but never stored, which meant the app's candlestick chart
  -- silently never had real data by the time a GET request reached it —
  -- fixed here rather than left quietly broken.
  recent_candles TEXT,                 -- JSON array of {time,open,high,low,close}
  smc_summary TEXT,                    -- JSON — see smc_analysis.py's analyze() output shape
  symbol_specs TEXT,                   -- JSON {tick_value,tick_size,contract_size,digits} — real broker data, see mt5_client.get_symbol_trade_specs

  -- status lifecycle:
  -- pending -> approved -> executed -> closed
  --         -> rejected_by_user
  --         -> skipped_by_agent        (legacy: old autonomous Worker auto-flow; no longer produced)
  --         (approved) -> rejected_by_risk   (bridge's risk layer rejected it after approval)
  --         (approved|pending) -> failed     (bridge reported an MT5 order_send failure — see POST /signals/:id/failed)
  --
  -- NOTE (migration): the Worker no longer auto-approves anything. A
  -- signal stays 'pending' until the subsystem's signal monitor or a
  -- human approves it. 'skipped_by_agent' rows can only come from legacy
  -- data; the new Worker never writes it.
  status TEXT NOT NULL DEFAULT 'pending',

  mt5_result TEXT,                     -- JSON blob of the MT5 order result, once executed
  rejection_reason TEXT,
  failure_reason TEXT,                 -- MT5 order_send failure detail (migration 0002 on existing DBs)

  -- Populated by exit_manager.py when it closes a position autonomously
  -- (trailing stop hit, breakeven stop hit, or time-based exit).
  closed_reason TEXT,
  closed_price REAL,
  closed_at TEXT,

  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);

-- Device push tokens for FCM. Supports multiple devices per install.
CREATE TABLE IF NOT EXISTS device_tokens (
  token TEXT PRIMARY KEY,
  registered_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_seen_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Simple key-value settings store. Currently used for:
--   trading_mode: 'manual' | 'autonomous'  (default 'manual' — see db.js)
--   kill_switch_engaged, kill_switch_close_all_requested_at
-- Legacy rows (custom_ai_url, custom_ai_api_key) from the old Worker may
-- still exist on upgraded databases — they are ignored and harmless.
-- Defaults to manual if no row exists, so a fresh deploy never
-- silently starts trading without approval.
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Real performance snapshots reported by performance_review.py, computed
-- from MT5's actual deal history — ground truth, not our own approximation.
CREATE TABLE IF NOT EXISTS performance_snapshots (
  id TEXT PRIMARY KEY,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  total_closed_trades INTEGER NOT NULL,
  wins INTEGER NOT NULL,
  losses INTEGER NOT NULL,
  breakeven INTEGER NOT NULL,
  win_rate_pct REAL,
  total_profit REAL NOT NULL,
  average_win REAL,
  average_loss REAL,
  profit_factor REAL,
  largest_win REAL,
  largest_loss REAL,
  by_symbol TEXT,                      -- JSON blob
  -- Real costs, summed from MT5's actual deal history across the same
  -- window — total_profit above is price-movement P/L only; net_profit
  -- is what actually happened to the account balance.
  total_commission REAL,
  total_swap REAL,
  net_profit REAL,                     -- total_profit + total_commission + total_swap
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_performance_created_at ON performance_snapshots(created_at);

-- Post-trade reflections: persisted when a signal closes. The reflection
-- TEXT is generated by the external agent (the Worker never calls an LLM);
-- see POST /signals/:id/closed's `reflection_text` field. Retrieval of
-- past reflections for future decisions is the subsystem's job.
CREATE TABLE IF NOT EXISTS reflections (
  id TEXT PRIMARY KEY,
  signal_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  direction TEXT NOT NULL,
  outcome TEXT NOT NULL,               -- 'win' | 'loss' | 'breakeven'
  entry_price REAL NOT NULL,
  closed_price REAL NOT NULL,
  original_reasoning TEXT,
  original_confidence INTEGER,
  reflection_text TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (signal_id) REFERENCES signals(id)
);

CREATE INDEX IF NOT EXISTS idx_reflections_symbol ON reflections(symbol);
CREATE INDEX IF NOT EXISTS idx_reflections_created_at ON reflections(created_at);

-- Chart data for the app's Charts tab — genuinely independent of the
-- signal pipeline, unlike signals.recent_candles (which exists only as
-- evidence for one specific trade decision). Refreshed on a schedule by
-- chart_data_loop in main.py, NOT live/streaming — updated_at is exposed
-- to the app precisely so it can show real staleness rather than imply
-- real-time data it doesn't have.
CREATE TABLE IF NOT EXISTS chart_data (
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL,
  candles TEXT NOT NULL,                -- JSON array of {time,open,high,low,close}
  ema_fast TEXT,                        -- JSON array, same length as candles, null-padded before warmup
  ema_slow TEXT,
  ema_fast_period INTEGER,
  ema_slow_period INTEGER,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (symbol, timeframe)
);

-- API clients: per-client credentials (replaces the old single shared
-- WORKER_API_KEY bearer secret). Secrets are stored as SHA-256 hex
-- digests only — never raw secrets. See docs/SECURITY.md and
-- scripts/provision-client.mjs.
CREATE TABLE IF NOT EXISTS api_clients (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the provision script
  client_id TEXT NOT NULL UNIQUE,      -- e.g. "bridge", "app", "agent"
  secret_hash TEXT NOT NULL,           -- SHA-256 hex of the client secret
  label TEXT,                          -- human note, e.g. "Windows MT5 bridge"
  revoked INTEGER NOT NULL DEFAULT 0,  -- 1 = credentials rejected
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_api_clients_client_id ON api_clients(client_id);
