/**
 * Post-trade reflection PERSISTENCE for the cloud/sync layer.
 *
 * The Worker never generates reflection text — that is the external
 * agent's job (see CORRELATION_RULE_NOTE.md for how the agent is expected
 * to use this). This module keeps the only Worker-side responsibility:
 * computing the deterministic outcome and storing the reflection RECORD
 * in the `reflections` D1 table when a signal closes.
 *
 * Kept from the original src/agent/reflect.js: `computeOutcome` (pure
 * math, unchanged) and the insert path. Removed: prompt building
 * (reflectPrompt.js) and every provider call (src/ai/*).
 */

import { insertReflection } from './db.js';

/** win/loss/breakeven from entry vs close price and direction — plain math, not opinion. */
export function computeOutcome(direction, entryPrice, closedPrice) {
  const diff = direction === 'BUY' ? closedPrice - entryPrice : entryPrice - closedPrice;
  if (diff > 0) return 'win';
  if (diff < 0) return 'loss';
  return 'breakeven';
}

/**
 * Store a reflection record for a closed signal.
 *
 * `reflectionText` may be supplied by the external agent / bridge when it
 * reports the close (POST /signals/:id/closed accepts `reflection_text`).
 * When it is absent, the record is still stored with a placeholder note so
 * the close itself is never lost — the agent can fill the text in later
 * via POST /signals/:id/reflection. Never throws for a missing text;
 * generation is not this layer's job.
 *
 * `signal` is the full D1 row for the closed signal (includes ai_reasoning,
 * ai_confidence, entry_price, closed_price, direction, symbol).
 * Returns the stored reflection row id.
 */
export async function recordReflection(db, signal, outcome, reflectionText = null) {
  const text =
    reflectionText && String(reflectionText).trim()
      ? String(reflectionText)
      : 'Reflection text not supplied — generated by the external agent, pending.';

  return insertReflection(db, {
    signal_id: signal.id,
    symbol: signal.symbol,
    direction: signal.direction,
    outcome,
    entry_price: signal.entry_price,
    closed_price: signal.closed_price,
    original_reasoning: signal.ai_reasoning,
    original_confidence: signal.ai_confidence,
    reflection_text: text,
  });
}
